In [2]:
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

import dice_ml
from dice_ml import Dice
from dice_ml.utils import helpers  # helper functions

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
dataset = helpers.load_adult_income_dataset().sample(5000)  # downsampling to reduce ML model fitting time
helpers.get_adult_data_info()

c:\Users\acbriza\anaconda3\envs\dpncf\Lib\site-packages\dice_ml\utils\helpers.py:70: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  adult_data = adult_data.replace({'income': {'<=50K': 0, '>50K': 1}})

{'age': 'age',
 'workclass': 'type of industry (Government, Other/Unknown, Private, Self-Employed)',
 'education': 'education level (Assoc, Bachelors, Doctorate, HS-grad, Masters, Prof-school, School, Some-college)',
 'marital_status': 'marital status (Divorced, Married, Separated, Single, Widowed)',
 'occupation': 'occupation (Blue-Collar, Other/Unknown, Professional, Sales, Service, White-Collar)',
 'race': 'white or other race?',
 'gender': 'male or female?',
 'hours_per_week': 'total work hours per week',
 'income': '0 (<=50K) vs 1 (>50K)'}

In [5]:
target = dataset["income"]

# Split data into train and test
datasetX = dataset.drop("income", axis=1)
x_train, x_test, y_train, y_test = train_test_split(datasetX,
                                                    target,
                                                    test_size=0.2,
                                                    random_state=0,
                                                    stratify=target)

numerical = ["age", "hours_per_week"]
categorical = x_train.columns.difference(numerical)

# We create the preprocessing pipelines for both numeric and categorical data.
numeric_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))])

transformations = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numerical),
        ('cat', categorical_transformer, categorical)])

# Append classifier to preprocessing pipeline.
# Now we have a full prediction pipeline.
clf = Pipeline(steps=[('preprocessor', transformations),
                      ('classifier', RandomForestClassifier())])
model = clf.fit(x_train, y_train)

In [6]:
d = dice_ml.Data(dataframe=dataset, continuous_features=['age', 'hours_per_week'], outcome_name='income')
m = dice_ml.Model(model=model, backend="sklearn")

In [7]:
exp = Dice(d, m, method="random")
query_instance = x_train[0:50]
e1 = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_range=None,
                                  desired_class="opposite",
                                  permitted_range=None, features_to_vary="all")

100%|██████████| 50/50 [00:13<00:00,  3.68it/s]

In [52]:
print([e.visualize_as_dataframe(show_only_changes=True) for e in e1.cf_examples_list[:10]])

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,50,Private,Bachelors,Married,Blue-Collar,White,Male,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,Sales,Other,-,-,1
1,-,-,-,-,-,-,-,90.0,1
2,-,Other/Unknown,-,-,Service,-,-,-,1
3,65.0,-,-,-,-,-,-,56.0,1
4,45.0,-,-,-,-,-,-,-,1
5,-,-,Prof-school,-,-,-,-,47.0,1
6,62.0,-,-,-,Sales,-,-,-,1
7,-,Self-Employed,Prof-school,-,-,-,-,-,1
8,46.0,-,-,-,-,-,-,86.0,1
9,-,-,-,-,Other/Unknown,-,-,75.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,50,Private,HS-grad,Married,Sales,Other,Female,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Bachelors,-,-,-,-,-,1
1,-,-,School,-,-,-,Male,-,1
2,71.0,-,Bachelors,-,-,-,-,-,1
3,-,-,Doctorate,-,-,-,-,-,1
4,70.0,-,Masters,-,-,-,-,-,1
5,-,-,Masters,-,White-Collar,-,-,-,1
6,-,-,Doctorate,-,-,-,Male,-,1
7,-,Government,Doctorate,-,-,-,-,-,1
8,68.0,-,Doctorate,-,-,-,-,-,1
9,-,Self-Employed,Bachelors,-,-,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,71,Self-Employed,Some-college,Separated,Sales,Other,Male,2,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,White,-,77.0,1
1,-,-,-,-,-,White,-,79.0,1
2,-,-,Doctorate,Married,-,-,-,-,1
3,-,-,Masters,-,-,-,-,94.0,-
4,-,-,-,-,-,White,-,97.0,1
5,-,-,-,Married,-,-,-,61.0,1
6,-,-,Masters,-,-,-,-,60.0,1
7,-,Private,-,-,-,-,-,66.0,1
8,-,-,Doctorate,-,-,-,-,99.0,1
9,-,Private,-,-,-,-,-,99.0,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,44,Private,Prof-school,Married,Professional,White,Male,50,1

Diverse Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Divorced,-,Other,-,-,0
1,28.0,-,-,-,-,-,-,-,0
2,81.0,-,-,Divorced,-,-,-,-,0
3,-,-,-,Divorced,White-Collar,-,-,-,0
4,-,-,-,Separated,-,-,-,-,0
5,49.0,-,HS-grad,-,-,-,-,-,0
6,-,-,Doctorate,Divorced,-,-,-,-,0
7,56.0,-,-,Widowed,-,-,-,-,0
8,-,-,-,Single,-,-,-,91.0,0
9,-,-,-,Separated,Blue-Collar,-,-,-,0

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,55,Government,Bachelors,Married,White-Collar,White,Male,38,1

Diverse Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,HS-grad,-,Sales,-,-,-,0
1,-,-,-,-,-,-,-,7.0,0
2,-,-,-,-,-,-,-,6.0,0
3,44.0,-,-,Widowed,-,-,-,-,0
4,86.0,-,-,-,-,-,-,-,0
5,17.0,-,-,-,Service,-,-,-,0
6,18.0,-,-,-,-,-,-,12.0,0
7,-,Private,-,-,Blue-Collar,-,-,-,0
8,-,-,-,Separated,-,-,-,90.0,0
9,-,-,-,Divorced,Sales,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,School,Married,Blue-Collar,White,Male,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,90.0,-,Doctorate,-,-,-,-,-,1
1,-,-,Prof-school,-,White-Collar,-,-,-,1
2,-,-,Some-college,-,White-Collar,-,-,-,1
3,-,-,Assoc,-,-,-,Female,-,1
4,-,Self-Employed,-,-,-,-,-,48.0,1
5,-,-,-,-,Professional,-,-,14.0,1
6,-,-,HS-grad,-,-,-,Female,-,1
7,-,Government,Doctorate,-,-,-,-,-,1
8,-,-,Doctorate,-,-,-,-,-,1
9,-,Other/Unknown,Assoc,-,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,Bachelors,Married,White-Collar,White,Male,40,1

Diverse Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,75.0,-,-,-,-,Other,-,-,0
1,-,-,-,-,Sales,-,-,-,0
2,-,-,-,Single,-,-,-,80.0,0
3,-,-,School,-,-,-,-,32.0,0
4,17.0,-,-,-,-,-,-,-,0
5,-,-,-,-,Service,-,-,-,0
6,45.0,-,-,Divorced,-,-,-,-,0
7,-,Government,-,Single,-,-,-,-,0
8,-,-,Assoc,-,Professional,-,-,-,0
9,-,-,Masters,-,-,-,-,7.0,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,42,Private,Some-college,Divorced,White-Collar,White,Male,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Masters,Separated,-,-,-,-,1
1,-,-,-,-,-,-,-,86.0,1
2,-,-,-,-,-,-,-,95.0,1
3,-,-,-,-,-,-,-,47.0,1
4,-,-,HS-grad,-,-,-,-,59.0,1
5,-,-,-,-,-,-,-,50.0,1
6,-,-,-,Married,-,Other,-,-,1
7,-,-,Bachelors,-,Sales,-,-,-,1
8,-,-,-,-,-,-,-,46.0,1
9,-,-,-,Married,-,-,-,54.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,33,Private,HS-grad,Single,Blue-Collar,Other,Female,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Married,-,-,Male,84.0,1
1,-,-,-,Married,-,-,Male,50.0,1
2,-,-,Doctorate,Married,Professional,-,-,-,1
3,63.0,-,Doctorate,-,-,White,-,-,1
4,-,-,-,Married,-,White,-,-,1
5,-,-,Doctorate,-,White-Collar,-,-,-,-
6,66.0,-,Doctorate,-,-,-,-,-,1
7,66.0,Self-Employed,Doctorate,-,-,-,-,-,1
8,-,-,Doctorate,Married,-,-,-,-,1
9,84.0,-,Doctorate,-,-,-,-,-,-

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,41,Private,HS-grad,Divorced,Service,White,Female,40,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,72.0,-,-,Married,-,-,Male,-,1
1,-,Government,-,Married,Blue-Collar,-,-,-,1
2,66.0,-,-,Married,-,-,Male,-,1
3,-,-,-,Married,Sales,-,Male,-,1
4,-,Government,Bachelors,Married,-,-,-,-,1
5,45.0,-,-,-,Blue-Collar,-,-,-,-
6,-,-,Bachelors,Married,-,-,Male,-,1
7,85.0,-,-,-,-,-,Male,60.0,1
8,-,-,-,Married,-,Other,Male,-,1
9,-,-,-,Married,-,-,Male,-,1

[None, None, None, None, None, None, None, None, None, None]

In [43]:
imp = exp.local_feature_importance(query_instance, cf_examples_list=e1.cf_examples_list)
print(imp.local_importance)

[{'hours_per_week': 0.5, 'occupation': 0.4, 'age': 0.4, 'workclass': 0.2, 'education': 0.2, 'race': 0.1, 'marital_status': 0.0, 'gender': 0.0}, {'education': 1.0, 'age': 0.3, 'workclass': 0.2, 'gender': 0.2, 'occupation': 0.1, 'marital_status': 0.0, 'race': 0.0, 'hours_per_week': 0.0}, {'hours_per_week': 0.9, 'education': 0.4, 'race': 0.3, 'workclass': 0.2, 'marital_status': 0.2, 'occupation': 0.0, 'gender': 0.0, 'age': 0.0}, {'marital_status': 0.8, 'age': 0.4, 'education': 0.2, 'occupation': 0.2, 'race': 0.1, 'hours_per_week': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'occupation': 0.4, 'age': 0.4, 'hours_per_week': 0.4, 'marital_status': 0.3, 'workclass': 0.1, 'education': 0.1, 'race': 0.0, 'gender': 0.0}, {'education': 0.8, 'workclass': 0.3, 'occupation': 0.3, 'gender': 0.2, 'hours_per_week': 0.2, 'age': 0.1, 'marital_status': 0.0, 'race': 0.0}, {'education': 0.3, 'marital_status': 0.3, 'occupation': 0.3, 'age': 0.3, 'hours_per_week': 0.3, 'workclass': 0.1, 'race': 0.1, 'gender': 0.0}, {'hours_per_week': 0.7, 'education': 0.3, 'marital_status': 0.3, 'occupation': 0.1, 'race': 0.1, 'workclass': 0.0, 'gender': 0.0, 'age': 0.0}, {'education': 0.7, 'marital_status': 0.5, 'age': 0.4, 'occupation': 0.2, 'race': 0.2, 'gender': 0.2, 'hours_per_week': 0.2, 'workclass': 0.1}, {'marital_status': 0.8, 'gender': 0.7, 'age': 0.4, 'occupation': 0.3, 'workclass': 0.2, 'education': 0.2, 'race': 0.1, 'hours_per_week': 0.1}, {'age': 0.6, 'marital_status': 0.5, 'hours_per_week': 0.4, 'gender': 0.2, 'occupation': 0.1, 'workclass': 0.0, 'education': 0.0, 'race': 0.0}, {'marital_status': 1.0, 'education': 0.9, 'age': 0.5, 'workclass': 0.2, 'occupation': 0.2, 'hours_per_week': 0.2, 'gender': 0.1, 'race': 0.0}, {'age': 0.6, 'occupation': 0.4, 'education': 0.3, 'marital_status': 0.1, 'gender': 0.1, 'hours_per_week': 0.1, 'workclass': 0.0, 'race': 0.0}, {'workclass': 0.5, 'occupation': 0.4, 'gender': 0.3, 'age': 0.3, 'education': 0.2, 'hours_per_week': 0.2, 'marital_status': 0.0, 'race': 0.0}, {'hours_per_week': 0.7, 'occupation': 0.4, 'gender': 0.4, 'workclass': 0.2, 'education': 0.2, 'age': 0.1, 'marital_status': 0.0, 'race': 0.0}, {'age': 0.9, 'hours_per_week': 0.9, 'education': 0.6, 'marital_status': 0.5, 'workclass': 0.1, 'occupation': 0.1, 'race': 0.1, 'gender': 0.0}, {'marital_status': 0.7, 'education': 0.6, 'age': 0.6, 'occupation': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'education': 0.5, 'occupation': 0.3, 'age': 0.3, 'hours_per_week': 0.3, 'workclass': 0.2, 'marital_status': 0.2, 'gender': 0.1, 'race': 0.0}, {'marital_status': 0.7, 'education': 0.5, 'age': 0.4, 'workclass': 0.1, 'occupation': 0.1, 'hours_per_week': 0.1, 'race': 0.0, 'gender': 0.0}, {'education': 0.8, 'hours_per_week': 0.3, 'marital_status': 0.2, 'occupation': 0.2, 'gender': 0.1, 'age': 0.1, 'workclass': 0.0, 'race': 0.0}, {'hours_per_week': 0.7, 'marital_status': 0.5, 'occupation': 0.2, 'workclass': 0.1, 'education': 0.1, 'race': 0.0, 'gender': 0.0, 'age': 0.0}, {'workclass': 0.3, 'occupation': 0.3, 'race': 0.3, 'hours_per_week': 0.3, 'education': 0.2, 'age': 0.2, 'marital_status': 0.1, 'gender': 0.1}, {'age': 0.6, 'hours_per_week': 0.6, 'workclass': 0.1, 'marital_status': 0.1, 'occupation': 0.1, 'race': 0.1, 'gender': 0.1, 'education': 0.0}, {'marital_status': 0.7, 'age': 0.7, 'education': 0.3, 'occupation': 0.2, 'race': 0.2, 'workclass': 0.1, 'gender': 0.1, 'hours_per_week': 0.1}, {'workclass': 0.4, 'hours_per_week': 0.4, 'marital_status': 0.3, 'age': 0.3, 'occupation': 0.2, 'race': 0.2, 'gender': 0.1, 'education': 0.0}, {'hours_per_week': 0.7, 'education': 0.6, 'age': 0.4, 'occupation': 0.1, 'workclass': 0.0, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.5, 'age': 0.5, 'hours_per_week': 0.5, 'workclass': 0.2, 'occupation': 0.1, 'race': 0.1, 'gender': 0.1, 'marital_status': 0.0}, {'hours_per_week': 0.8, 'age': 0.4, 'occupation': 0.1, 'race': 0.1, 'workclass': 0.0, 'education': 0.0, 'marital_status': 0.0, 'gender': 0.0}, {'occupation': 0.8, 'age': 0.8, 'education': 0.7, 'hours_per_week': 0.5, 'marital_status': 0.4, 'workclass': 0.3, 'gender': 0.1, 'race': 0.0}, {'age': 0.9, 'hours_per_week': 0.9, 'education': 0.1, 'marital_status': 0.1, 'workclass': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'occupation': 0.5, 'gender': 0.3, 'hours_per_week': 0.3, 'workclass': 0.2, 'education': 0.2, 'age': 0.2, 'race': 0.1, 'marital_status': 0.0}, {'age': 0.9, 'gender': 0.7, 'marital_status': 0.3, 'occupation': 0.1, 'workclass': 0.0, 'education': 0.0, 'race': 0.0, 'hours_per_week': 0.0}, {'age': 0.8, 'hours_per_week': 0.6, 'marital_status': 0.2, 'workclass': 0.0, 'education': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.9, 'age': 0.8, 'hours_per_week': 0.5, 'occupation': 0.4, 'education': 0.3, 'gender': 0.2, 'workclass': 0.1, 'race': 0.1}, {'age': 0.6, 'education': 0.3, 'race': 0.3, 'hours_per_week': 0.3, 'workclass': 0.1, 'marital_status': 0.1, 'occupation': 0.0, 'gender': 0.0}, {'age': 0.5, 'hours_per_week': 0.4, 'workclass': 0.3, 'education': 0.2, 'occupation': 0.2, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.6, 'hours_per_week': 0.4, 'marital_status': 0.3, 'occupation': 0.3, 'age': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.8, 'marital_status': 0.4, 'hours_per_week': 0.4, 'age': 0.2, 'occupation': 0.1, 'race': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'marital_status': 0.7, 'education': 0.3, 'occupation': 0.3, 'age': 0.3, 'workclass': 0.2, 'hours_per_week': 0.2, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 0.6, 'marital_status': 0.5, 'age': 0.5, 'gender': 0.2, 'workclass': 0.1, 'education': 0.1, 'occupation': 0.0, 'race': 0.0}, {'age': 0.9, 'education': 0.5, 'occupation': 0.4, 'workclass': 0.2, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'marital_status': 1.0, 'age': 0.5, 'hours_per_week': 0.3, 'occupation': 0.2, 'workclass': 0.0, 'education': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.7, 'occupation': 0.5, 'education': 0.3, 'hours_per_week': 0.3, 'workclass': 0.0, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.9, 'education': 0.8, 'occupation': 0.3, 'hours_per_week': 0.3, 'marital_status': 0.2, 'workclass': 0.1, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.6, 'occupation': 0.5, 'education': 0.3, 'gender': 0.3, 'workclass': 0.1, 'race': 0.1, 'age': 0.1, 'hours_per_week': 0.0}, {'hours_per_week': 0.7, 'education': 0.5, 'occupation': 0.4, 'age': 0.3, 'workclass': 0.1, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.5, 'marital_status': 0.4, 'age': 0.4, 'gender': 0.2, 'hours_per_week': 0.2, 'workclass': 0.1, 'race': 0.1, 'occupation': 0.0}, {'marital_status': 0.7, 'age': 0.4, 'hours_per_week': 0.4, 'occupation': 0.2, 'workclass': 0.1, 'education': 0.1, 'race': 0.0, 'gender': 0.0}, {'age': 0.5, 'hours_per_week': 0.4, 'occupation': 0.2, 'education': 0.1, 'race': 0.1, 'gender': 0.1, 'workclass': 0.0, 'marital_status': 0.0}, {'marital_status': 1.0, 'age': 0.5, 'workclass': 0.2, 'hours_per_week': 0.2, 'gender': 0.1, 'education': 0.0, 'occupation': 0.0, 'race': 0.0}]

In [46]:
imp = exp.local_feature_importance(query_instance, posthoc_sparsity_param=None)
print(imp.local_importance)

100%|██████████| 50/50 [00:02<00:00, 19.13it/s]

[{'age': 0.7, 'occupation': 0.6, 'workclass': 0.2, 'hours_per_week': 0.2, 'race': 0.1, 'education': 0.0, 'marital_status': 0.0, 'gender': 0.0}, {'education': 0.8, 'age': 0.4, 'gender': 0.3, 'hours_per_week': 0.2, 'race': 0.1, 'workclass': 0.0, 'marital_status': 0.0, 'occupation': 0.0}, {'hours_per_week': 1.0, 'education': 0.4, 'workclass': 0.2, 'race': 0.2, 'marital_status': 0.1, 'age': 0.1, 'occupation': 0.0, 'gender': 0.0}, {'marital_status': 0.6, 'occupation': 0.4, 'age': 0.4, 'hours_per_week': 0.3, 'gender': 0.1, 'workclass': 0.0, 'education': 0.0, 'race': 0.0}, {'marital_status': 0.6, 'education': 0.3, 'occupation': 0.3, 'age': 0.3, 'hours_per_week': 0.3, 'workclass': 0.1, 'race': 0.0, 'gender': 0.0}, {'education': 1.0, 'hours_per_week': 0.3, 'workclass': 0.2, 'occupation': 0.2, 'race': 0.2, 'age': 0.1, 'marital_status': 0.0, 'gender': 0.0}, {'age': 0.5, 'hours_per_week': 0.4, 'occupation': 0.2, 'race': 0.2, 'gender': 0.2, 'workclass': 0.1, 'education': 0.1, 'marital_status': 0.1}, {'marital_status': 0.6, 'hours_per_week': 0.5, 'education': 0.4, 'occupation': 0.1, 'race': 0.1, 'age': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'education': 0.6, 'marital_status': 0.5, 'race': 0.5, 'occupation': 0.3, 'age': 0.3, 'gender': 0.2, 'hours_per_week': 0.2, 'workclass': 0.1}, {'marital_status': 0.9, 'gender': 0.6, 'occupation': 0.4, 'education': 0.3, 'workclass': 0.2, 'hours_per_week': 0.2, 'race': 0.1, 'age': 0.1}, {'hours_per_week': 0.7, 'age': 0.5, 'workclass': 0.1, 'marital_status': 0.1, 'gender': 0.1, 'education': 0.0, 'occupation': 0.0, 'race': 0.0}, {'education': 0.9, 'marital_status': 0.9, 'hours_per_week': 0.6, 'occupation': 0.4, 'gender': 0.3, 'age': 0.2, 'workclass': 0.1, 'race': 0.0}, {'marital_status': 0.6, 'age': 0.5, 'occupation': 0.4, 'education': 0.1, 'hours_per_week': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'occupation': 0.6, 'workclass': 0.3, 'gender': 0.3, 'age': 0.3, 'hours_per_week': 0.3, 'education': 0.2, 'marital_status': 0.0, 'race': 0.0}, {'occupation': 0.5, 'hours_per_week': 0.4, 'education': 0.3, 'gender': 0.3, 'workclass': 0.2, 'age': 0.2, 'race': 0.1, 'marital_status': 0.0}, {'age': 1.0, 'hours_per_week': 0.8, 'marital_status': 0.7, 'education': 0.3, 'occupation': 0.3, 'workclass': 0.1, 'gender': 0.1, 'race': 0.0}, {'marital_status': 0.7, 'age': 0.7, 'education': 0.6, 'workclass': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'marital_status': 0.6, 'age': 0.5, 'education': 0.3, 'occupation': 0.3, 'hours_per_week': 0.2, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.6, 'marital_status': 0.5, 'age': 0.5, 'hours_per_week': 0.2, 'workclass': 0.1, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.9, 'workclass': 0.3, 'occupation': 0.2, 'age': 0.2, 'race': 0.1, 'gender': 0.1, 'hours_per_week': 0.1, 'marital_status': 0.0}, {'hours_per_week': 0.7, 'marital_status': 0.3, 'occupation': 0.2, 'race': 0.2, 'age': 0.2, 'education': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'hours_per_week': 0.4, 'workclass': 0.3, 'age': 0.3, 'occupation': 0.2, 'gender': 0.2, 'marital_status': 0.1, 'race': 0.1, 'education': 0.0}, {'hours_per_week': 0.6, 'age': 0.5, 'marital_status': 0.3, 'workclass': 0.1, 'education': 0.1, 'occupation': 0.1, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.7, 'age': 0.7, 'education': 0.4, 'workclass': 0.3, 'occupation': 0.3, 'race': 0.1, 'gender': 0.0, 'hours_per_week': 0.0}, {'age': 0.7, 'marital_status': 0.3, 'hours_per_week': 0.3, 'occupation': 0.2, 'workclass': 0.1, 'education': 0.1, 'race': 0.1, 'gender': 0.0}, {'hours_per_week': 0.7, 'education': 0.6, 'age': 0.2, 'workclass': 0.1, 'occupation': 0.1, 'gender': 0.1, 'marital_status': 0.0, 'race': 0.0}, {'education': 0.8, 'hours_per_week': 0.5, 'workclass': 0.2, 'race': 0.2, 'age': 0.2, 'occupation': 0.1, 'marital_status': 0.0, 'gender': 0.0}, {'hours_per_week': 0.7, 'age': 0.5, 'race': 0.2, 'occupation': 0.1, 'workclass': 0.0, 'education': 0.0, 'marital_status': 0.0, 'gender': 0.0}, {'age': 1.0, 'marital_status': 0.6, 'education': 0.5, 'occupation': 0.4, 'gender': 0.3, 'hours_per_week': 0.3, 'workclass': 0.2, 'race': 0.0}, {'age': 1.0, 'hours_per_week': 1.0, 'workclass': 0.0, 'education': 0.0, 'marital_status': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 0.6, 'education': 0.4, 'age': 0.4, 'occupation': 0.3, 'workclass': 0.1, 'race': 0.1, 'marital_status': 0.0, 'gender': 0.0}, {'age': 1.0, 'marital_status': 0.5, 'education': 0.4, 'gender': 0.1, 'workclass': 0.0, 'occupation': 0.0, 'race': 0.0, 'hours_per_week': 0.0}, {'age': 0.5, 'marital_status': 0.4, 'hours_per_week': 0.4, 'occupation': 0.2, 'education': 0.1, 'gender': 0.1, 'workclass': 0.0, 'race': 0.0}, {'age': 1.0, 'marital_status': 0.7, 'hours_per_week': 0.6, 'education': 0.4, 'occupation': 0.4, 'race': 0.3, 'gender': 0.1, 'workclass': 0.0}, {'age': 0.5, 'marital_status': 0.3, 'workclass': 0.2, 'race': 0.2, 'hours_per_week': 0.2, 'education': 0.1, 'occupation': 0.1, 'gender': 0.1}, {'age': 0.6, 'hours_per_week': 0.4, 'workclass': 0.2, 'education': 0.1, 'gender': 0.1, 'marital_status': 0.0, 'occupation': 0.0, 'race': 0.0}, {'education': 0.4, 'age': 0.4, 'workclass': 0.3, 'hours_per_week': 0.3, 'marital_status': 0.2, 'occupation': 0.1, 'race': 0.0, 'gender': 0.0}, {'age': 0.7, 'race': 0.5, 'education': 0.4, 'marital_status': 0.2, 'hours_per_week': 0.2, 'workclass': 0.0, 'occupation': 0.0, 'gender': 0.0}, {'marital_status': 0.7, 'education': 0.6, 'occupation': 0.3, 'age': 0.2, 'race': 0.1, 'hours_per_week': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'hours_per_week': 0.6, 'marital_status': 0.4, 'gender': 0.3, 'age': 0.3, 'education': 0.2, 'occupation': 0.2, 'workclass': 0.0, 'race': 0.0}, {'age': 0.8, 'education': 0.6, 'occupation': 0.4, 'workclass': 0.1, 'marital_status': 0.1, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'marital_status': 1.0, 'hours_per_week': 0.4, 'age': 0.3, 'occupation': 0.2, 'education': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'occupation': 0.6, 'age': 0.5, 'workclass': 0.2, 'education': 0.2, 'race': 0.2, 'marital_status': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'education': 0.9, 'age': 0.8, 'marital_status': 0.6, 'workclass': 0.3, 'occupation': 0.3, 'hours_per_week': 0.1, 'race': 0.0, 'gender': 0.0}, {'education': 0.6, 'marital_status': 0.4, 'occupation': 0.4, 'gender': 0.3, 'workclass': 0.2, 'race': 0.1, 'age': 0.0, 'hours_per_week': 0.0}, {'education': 0.8, 'occupation': 0.3, 'age': 0.3, 'workclass': 0.2, 'hours_per_week': 0.2, 'marital_status': 0.1, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.5, 'education': 0.4, 'age': 0.3, 'hours_per_week': 0.3, 'workclass': 0.2, 'gender': 0.1, 'occupation': 0.0, 'race': 0.0}, {'marital_status': 0.6, 'education': 0.5, 'age': 0.4, 'hours_per_week': 0.4, 'occupation': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.6, 'hours_per_week': 0.4, 'education': 0.2, 'occupation': 0.2, 'workclass': 0.1, 'gender': 0.1, 'marital_status': 0.0, 'race': 0.0}, {'marital_status': 0.9, 'age': 0.6, 'education': 0.2, 'workclass': 0.1, 'occupation': 0.1, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}]

In [48]:
cobj = exp.global_feature_importance(x_train[0:50], total_CFs=10, posthoc_sparsity_param=None)
print(cobj.summary_importance)

100%|██████████| 50/50 [00:02<00:00, 17.81it/s]

{'age': 0.432, 'hours_per_week': 0.4, 'marital_status': 0.392, 'education': 0.324, 'occupation': 0.2, 'workclass': 0.138, 'race': 0.082, 'gender': 0.08}

In [49]:
json_str = cobj.to_json()
print(json_str)

{"test_data": [[[50, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 40, 0]], [[50, "Private", "HS-grad", "Married", "Sales", "Other", "Female", 40, 0]], [[71, "Self-Employed", "Some-college", "Separated", "Sales", "Other", "Male", 2, 0]], [[44, "Private", "Prof-school", "Married", "Professional", "White", "Male", 50, 1]], [[55, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 1]], [[38, "Private", "School", "Married", "Blue-Collar", "White", "Male", 40, 0]], [[38, "Private", "Bachelors", "Married", "White-Collar", "White", "Male", 40, 1]], [[42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 40, 0]], [[33, "Private", "HS-grad", "Single", "Blue-Collar", "Other", "Female", 40, 0]], [[41, "Private", "HS-grad", "Divorced", "Service", "White", "Female", 40, 0]], [[47, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 1]], [[69, "Other/Unknown", "HS-grad", "Widowed", "Other/Unknown", "White", "Female", 9, 0]], [[62, "Private", "Assoc", "Married", "White-Collar", "White", "Female", 45, 1]], [[33, "Self-Employed", "Assoc", "Married", "Blue-Collar", "White", "Male", 65, 0]], [[44, "Government", "Assoc", "Married", "Blue-Collar", "White", "Male", 30, 0]], [[25, "Private", "Some-college", "Single", "Service", "White", "Male", 25, 0]], [[27, "Private", "Assoc", "Single", "White-Collar", "White", "Male", 50, 0]], [[44, "Private", "Bachelors", "Married", "White-Collar", "White", "Male", 50, 1]], [[31, "Private", "HS-grad", "Single", "Blue-Collar", "White", "Female", 40, 0]], [[51, "Government", "HS-grad", "Married", "White-Collar", "White", "Female", 32, 0]], [[47, "Private", "Masters", "Divorced", "Service", "White", "Male", 40, 0]], [[50, "Self-Employed", "Doctorate", "Married", "Professional", "White", "Male", 40, 0]], [[49, "Private", "Some-college", "Married", "Sales", "White", "Male", 80, 1]], [[22, "Private", "HS-grad", "Single", "Blue-Collar", "White", "Male", 40, 0]], [[56, "Private", "HS-grad", "Married", "White-Collar", "White", "Male", 40, 1]], [[33, "Private", "HS-grad", "Married", "Sales", "White", "Male", 20, 0]], [[57, "Private", "HS-grad", "Married", "Service", "White", "Male", 30, 0]], [[72, "Private", "Bachelors", "Married", "Service", "White", "Male", 17, 0]], [[19, "Private", "Some-college", "Single", "Service", "White", "Female", 15, 0]], [[44, "Private", "HS-grad", "Divorced", "Blue-Collar", "Other", "Male", 20, 0]], [[48, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 40, 0]], [[24, "Private", "Bachelors", "Single", "White-Collar", "White", "Male", 40, 0]], [[43, "Government", "Masters", "Divorced", "Professional", "White", "Male", 40, 0]], [[22, "Private", "HS-grad", "Single", "Blue-Collar", "White", "Male", 35, 0]], [[39, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1]], [[38, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Male", 40, 0]], [[55, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Male", 53, 1]], [[42, "Self-Employed", "HS-grad", "Single", "White-Collar", "White", "Male", 48, 0]], [[52, "Private", "HS-grad", "Widowed", "Blue-Collar", "White", "Male", 40, 0]], [[37, "Private", "Masters", "Single", "Professional", "White", "Female", 40, 0]], [[26, "Private", "School", "Married", "White-Collar", "White", "Male", 40, 0]], [[38, "Private", "Assoc", "Divorced", "White-Collar", "White", "Female", 16, 0]], [[28, "Self-Employed", "Some-college", "Married", "Blue-Collar", "White", "Male", 55, 0]], [[22, "Private", "HS-grad", "Single", "Service", "Other", "Male", 30, 0]], [[54, "Private", "Bachelors", "Single", "Service", "Other", "Female", 36, 0]], [[62, "Private", "School", "Married", "Sales", "White", "Male", 35, 0]], [[39, "Private", "Bachelors", "Divorced", "White-Collar", "White", "Male", 50, 0]], [[46, "Self-Employed", "Doctorate", "Married", "Professional", "White", "Male", 50, 1]], [[43, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Male", 40, 0]], [[28, "Government", "Doctorate", "Divorced", "Professional", "White", "Female", 40, 0]]], "cfs_list": [[[46.0, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Female", 40, 1], [43.0, "Private", "Bachelors", "Married", "Blue-Collar", "Other", "Male", 40, 1], [50, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 96.0, 1], [50, "Private", "Bachelors", "Married", "Blue-Collar", "Other", "Male", 79.0, 1], [50, "Private", "Bachelors", "Widowed", "Sales", "White", "Male", 40, 1], [63.0, "Private", "Bachelors", "Married", "Blue-Collar", "Other", "Male", 40, 1], [59.0, "Private", "Bachelors", "Married", "Sales", "White", "Male", 40, 1], [50, "Self-Employed", "Bachelors", "Married", "Sales", "White", "Male", 40, 1], [50, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 90.0, 1], [50, "Private", "Bachelors", "Married", "Blue-Collar", "Other", "Male", 59.0, 1]], [[60.0, "Private", "Doctorate", "Married", "Sales", "Other", "Female", 40, 1], [68.0, "Private", "Doctorate", "Married", "Sales", "Other", "Female", 40, 1], [57.0, "Private", "Bachelors", "Married", "Sales", "Other", "Female", 40, 1], [50, "Private", "Masters", "Married", "Sales", "Other", "Male", 40, 1], [50, "Private", "Assoc", "Married", "Professional", "Other", "Female", 40, 1], [50, "Private", "Doctorate", "Married", "Sales", "Other", "Female", 91.0, 1], [50, "Private", "Masters", "Married", "Sales", "Other", "Female", 40, 1], [50, "Other/Unknown", "Masters", "Married", "Sales", "Other", "Female", 40, 1], [50, "Private", "Doctorate", "Married", "Other/Unknown", "Other", "Female", 40, 1], [50, "Private", "School", "Married", "Sales", "Other", "Male", 40, 1]], [[71, "Self-Employed", "Bachelors", "Separated", "Sales", "Other", "Male", 56.0, 1], [71, "Self-Employed", "Some-college", "Separated", "Sales", "White", "Male", 47.0, 1], [71, "Self-Employed", "Doctorate", "Married", "Sales", "Other", "Male", 2, 1], [71, "Self-Employed", "Prof-school", "Separated", "Sales", "Other", "Male", 99.0, 1], [71, "Self-Employed", "Bachelors", "Separated", "Sales", "Other", "Male", 81.0, 1], [71, "Private", "Some-college", "Separated", "Sales", "Other", "Male", 75.0, 1], [71, "Self-Employed", "Some-college", "Separated", "Sales", "White", "Male", 48.0, 1], [71, "Private", "Some-college", "Separated", "Sales", "Other", "Male", 93.0, 1], [71, "Self-Employed", "Some-college", "Separated", "Sales", "White", "Male", 45.0, 1], [71, "Self-Employed", "Some-college", "Married", "Sales", "Other", "Male", 51.0, 1]], [[44, "Private", "Prof-school", "Single", "Professional", "White", "Male", 33.0, 0], [90.0, "Private", "Prof-school", "Widowed", "Professional", "White", "Male", 50, 0], [44, "Private", "Prof-school", "Separated", "Professional", "White", "Male", 47.0, 0], [27.0, "Private", "Bachelors", "Married", "Professional", "White", "Male", 50, 0], [44, "Private", "Prof-school", "Married", "Sales", "White", "Male", 15.0, 0], [20.0, "Private", "Prof-school", "Married", "Professional", "White", "Male", 50, 0], [19.0, "Private", "HS-grad", "Married", "Professional", "White", "Male", 50, 0], [22.0, "Private", "Prof-school", "Married", "Blue-Collar", "White", "Male", 50, 0], [18.0, "Private", "Prof-school", "Married", "Professional", "White", "Male", 50, 0], [44, "Private", "Prof-school", "Widowed", "Sales", "White", "Male", 50, 0]], [[23.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 0], [55, "Government", "School", "Married", "White-Collar", "White", "Male", 69.0, 0], [88.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 0], [59.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 20.0, 0], [55, "Government", "Bachelors", "Separated", "White-Collar", "White", "Male", 38, 0], [55, "Private", "Bachelors", "Divorced", "White-Collar", "White", "Male", 38, 0], [25.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 0], [77.0, "Government", "Bachelors", "Widowed", "White-Collar", "White", "Male", 38, 0], [64.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 0], [72.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 38, 0]], [[38, "Other/Unknown", "Doctorate", "Married", "Blue-Collar", "White", "Male", 40, 1], [38, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [38, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 72.0, 1], [38, "Private", "School", "Married", "Blue-Collar", "Other", "Male", 88.0, 1], [38, "Private", "HS-grad", "Married", "Blue-Collar", "Other", "Male", 40, 1], [38, "Private", "Masters", "Married", "Blue-Collar", "White", "Female", 40, 1], [38, "Private", "Doctorate", "Married", "Blue-Collar", "White", "Female", 40, 1], [51.0, "Private", "Prof-school", "Married", "Blue-Collar", "White", "Male", 40, 1], [38, "Private", "Doctorate", "Married", "Blue-Collar", "Other", "Male", 40, 1], [38, "Private", "School", "Married", "Blue-Collar", "White", "Male", 59.0, 1]], [[62.0, "Private", "Bachelors", "Married", "White-Collar", "White", "Female", 40, 0], [73.0, "Private", "Bachelors", "Single", "White-Collar", "White", "Male", 40, 0], [37.0, "Private", "Bachelors", "Single", "White-Collar", "White", "Male", 40, 0], [38, "Private", "Bachelors", "Widowed", "White-Collar", "White", "Male", 15.0, 0], [38, "Private", "HS-grad", "Divorced", "White-Collar", "White", "Male", 40, 0], [84.0, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 40, 0], [38, "Private", "Assoc", "Single", "White-Collar", "White", "Male", 40, 0], [63.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 40, 0], [38, "Private", "Assoc", "Divorced", "White-Collar", "White", "Male", 40, 0], [27.0, "Private", "Masters", "Married", "White-Collar", "White", "Male", 40, 0]], [[42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 52.0, 1], [42, "Private", "Some-college", "Separated", "White-Collar", "White", "Male", 57.0, 1], [42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 55.0, 1], [42, "Private", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 1], [42, "Private", "Doctorate", "Single", "White-Collar", "White", "Male", 40, 1], [42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 88.0, 1], [42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 98.0, 1], [42, "Private", "Some-college", "Married", "White-Collar", "White", "Male", 83.0, 1], [42, "Private", "Bachelors", "Married", "White-Collar", "White", "Male", 40, 1], [42, "Private", "Some-college", "Divorced", "White-Collar", "White", "Male", 86.0, 1]], [[33, "Private", "Doctorate", "Single", "White-Collar", "Other", "Female", 40, 0], [33, "Private", "Prof-school", "Single", "Sales", "Other", "Male", 40, 1], [33, "Government", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [33, "Self-Employed", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [33, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 97.0, 1], [70.0, "Private", "Doctorate", "Single", "Sales", "Other", "Female", 40, 1], [56.0, "Private", "Doctorate", "Single", "Blue-Collar", "Other", "Female", 19.0, 1], [33, "Private", "Doctorate", "Married", "Blue-Collar", "Other", "Female", 40, 1], [33, "Private", "Masters", "Married", "Blue-Collar", "White", "Female", 40, 1], [33, "Private", "Doctorate", "Married", "Blue-Collar", "Other", "Female", 67.0, 1]], [[41, "Private", "HS-grad", "Married", "Service", "White", "Male", 52.0, 1], [41, "Private", "HS-grad", "Married", "Service", "Other", "Male", 40, 1], [41, "Private", "HS-grad", "Married", "Service", "White", "Male", 99.0, 1], [68.0, "Private", "HS-grad", "Married", "Service", "White", "Male", 40, 1], [41, "Private", "HS-grad", "Married", "White-Collar", "White", "Female", 40, 1], [41, "Self-Employed", "HS-grad", "Married", "Service", "White", "Male", 40, 1], [61.0, "Private", "HS-grad", "Married", "Service", "White", "Male", 40, 1], [41, "Private", "HS-grad", "Married", "Service", "White", "Male", 40, 1], [41, "Private", "HS-grad", "Married", "Service", "White", "Male", 43.0, 1], [41, "Private", "HS-grad", "Divorced", "White-Collar", "White", "Male", 95.0, 1]], [[17.0, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 0], [47, "Government", "Bachelors", "Married", "Blue-Collar", "White", "Male", 19.0, 0], [36.0, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 0], [75.0, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 0], [47, "Government", "Some-college", "Widowed", "Blue-Collar", "White", "Male", 27.0, 0], [47, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 31.0, 0], [47, "Self-Employed", "Some-college", "Married", "Blue-Collar", "White", "Male", 88.0, 0], [47, "Self-Employed", "Some-college", "Married", "Sales", "White", "Male", 40, 0], [68.0, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 40, 0], [31.0, "Government", "Some-college", "Separated", "Blue-Collar", "White", "Male", 40, 0]], [[69, "Private", "Masters", "Married", "Other/Unknown", "White", "Female", 80.0, 1], [69, "Other/Unknown", "Masters", "Married", "Other/Unknown", "Other", "Female", 53.0, 1], [69, "Other/Unknown", "Doctorate", "Single", "Sales", "White", "Female", 9, 1], [69, "Other/Unknown", "Doctorate", "Single", "Other/Unknown", "White", "Female", 9, 0], [69, "Other/Unknown", "Masters", "Married", "Other/Unknown", "White", "Female", 83.0, 1], [69, "Other/Unknown", "HS-grad", "Married", "Other/Unknown", "White", "Male", 53.0, 1], [69, "Other/Unknown", "Masters", "Married", "Other/Unknown", "White", "Female", 84.0, 1], [69, "Private", "Masters", "Married", "Other/Unknown", "White", "Female", 9, 1], [46.0, "Other/Unknown", "Doctorate", "Single", "Sales", "White", "Female", 9, 1], [69, "Self-Employed", "Doctorate", "Single", "Other/Unknown", "White", "Female", 9, 1]], [[62, "Private", "Assoc", "Married", "Other/Unknown", "White", "Female", 84.0, 0], [62, "Private", "Assoc", "Divorced", "White-Collar", "White", "Female", 70.0, 0], [62, "Private", "Bachelors", "Married", "White-Collar", "White", "Female", 67.0, 0], [83.0, "Private", "Assoc", "Separated", "White-Collar", "White", "Female", 45, 0], [62, "Private", "Bachelors", "Widowed", "White-Collar", "White", "Female", 45, 0], [44.0, "Private", "Assoc", "Single", "White-Collar", "White", "Female", 45, 0], [62, "Private", "HS-grad", "Separated", "White-Collar", "White", "Female", 45, 0], [37.0, "Private", "Assoc", "Single", "White-Collar", "White", "Female", 45, 0], [62, "Private", "Assoc", "Widowed", "White-Collar", "White", "Female", 73.0, 0], [62, "Private", "Assoc", "Separated", "Other/Unknown", "White", "Female", 45, 0]], [[33, "Government", "Assoc", "Married", "Other/Unknown", "White", "Male", 65, 1], [45.0, "Self-Employed", "Assoc", "Married", "Sales", "White", "Male", 65, 1], [33, "Self-Employed", "Assoc", "Married", "Blue-Collar", "White", "Female", 45.0, 1], [33, "Self-Employed", "HS-grad", "Married", "Blue-Collar", "White", "Male", 98.0, 1], [57.0, "Self-Employed", "Bachelors", "Married", "Blue-Collar", "White", "Male", 65, 1], [33, "Other/Unknown", "Assoc", "Married", "White-Collar", "White", "Male", 65, 1], [33, "Self-Employed", "Assoc", "Married", "Professional", "White", "Male", 63.0, 1], [52.0, "Self-Employed", "Bachelors", "Married", "Blue-Collar", "White", "Male", 65, 1], [33, "Private", "Bachelors", "Married", "Blue-Collar", "White", "Male", 65, 1], [33, "Self-Employed", "Assoc", "Married", "Sales", "White", "Female", 65, 1]], [[44, "Government", "Assoc", "Married", "Sales", "White", "Male", 85.0, 1], [63.0, "Government", "Assoc", "Married", "Professional", "White", "Male", 30, 1], [44, "Government", "HS-grad", "Married", "White-Collar", "White", "Male", 30, 1], [44, "Government", "Doctorate", "Married", "Other/Unknown", "White", "Male", 30, 1], [44, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 30, 1], [44, "Government", "Some-college", "Married", "Blue-Collar", "White", "Male", 42.0, 1], [44, "Government", "Prof-school", "Married", "Professional", "White", "Male", 30, 1], [44, "Government", "Doctorate", "Married", "White-Collar", "White", "Male", 30, 1], [61.0, "Government", "Assoc", "Married", "Professional", "White", "Male", 30, 1], [44, "Other/Unknown", "Assoc", "Married", "Professional", "White", "Male", 30, 1]], [[67.0, "Private", "Doctorate", "Married", "Service", "Other", "Male", 25, 1], [34.0, "Private", "Some-college", "Married", "Service", "White", "Male", 48.0, 1], [34.0, "Private", "Some-college", "Married", "Service", "White", "Male", 98.0, 1], [25, "Private", "Some-college", "Married", "Blue-Collar", "White", "Male", 73.0, 1], [61.0, "Private", "Doctorate", "Married", "Service", "White", "Male", 25, 1], [25, "Private", "Bachelors", "Married", "Service", "White", "Male", 25, 1], [86.0, "Private", "Some-college", "Separated", "Service", "White", "Male", 92.0, 1], [77.0, "Private", "Some-college", "Married", "Service", "White", "Male", 91.0, 1], [84.0, "Private", "Some-college", "Married", "Professional", "White", "Male", 93.0, 1], [68.0, "Self-Employed", "Some-college", "Married", "Service", "White", "Male", 35.0, 1]], [[27, "Private", "Bachelors", "Married", "White-Collar", "White", "Male", 50, 1], [86.0, "Private", "Assoc", "Married", "White-Collar", "White", "Male", 50, 1], [34.0, "Private", "Assoc", "Married", "White-Collar", "White", "Male", 50, 1], [63.0, "Private", "Assoc", "Married", "White-Collar", "White", "Male", 50, 1], [79.0, "Private", "Assoc", "Married", "White-Collar", "White", "Male", 50, 1], [27, "Private", "Prof-school", "Married", "White-Collar", "White", "Male", 50, 1], [27, "Private", "Doctorate", "Married", "White-Collar", "White", "Male", 50, 1], [62.0, "Private", "Masters", "Single", "White-Collar", "White", "Male", 50, 1], [72.0, "Private", "Assoc", "Married", "White-Collar", "White", "Male", 50, 1], [85.0, "Private", "Masters", "Single", "White-Collar", "White", "Male", 50, 1]], [[46.0, "Private", "Bachelors", "Widowed", "White-Collar", "White", "Male", 50, 0], [24.0, "Private", "Bachelors", "Married", "White-Collar", "White", "Male", 50, 0], [44, "Private", "School", "Separated", "White-Collar", "White", "Male", 50, 0], [44, "Private", "Bachelors", "Single", "White-Collar", "White", "Male", 85.0, 0], [44, "Private", "HS-grad", "Married", "White-Collar", "White", "Male", 6.0, 0], [19.0, "Government", "Bachelors", "Married", "White-Collar", "White", "Male", 50, 0], [44, "Private", "Bachelors", "Divorced", "White-Collar", "White", "Male", 50, 0], [82.0, "Private", "Bachelors", "Separated", "White-Collar", "White", "Male", 50, 0], [70.0, "Private", "Bachelors", "Divorced", "White-Collar", "White", "Male", 50, 0], [44, "Government", "School", "Married", "White-Collar", "White", "Male", 50, 0]], [[31, "Self-Employed", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [43.0, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [31, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [31, "Government", "HS-grad", "Married", "Blue-Collar", "White", "Female", 40, 1], [31, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 96.0, 1], [31, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 98.0, 1], [31, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 51.0, 1], [31, "Private", "Prof-school", "Married", "Blue-Collar", "White", "Female", 40, 1], [86.0, "Private", "Doctorate", "Single", "Blue-Collar", "White", "Female", 40, 1], [31, "Private", "HS-grad", "Married", "Blue-Collar", "White", "Female", 36.0, 1]], [[51, "Government", "Doctorate", "Married", "White-Collar", "White", "Female", 83.0, 1], [51, "Government", "Doctorate", "Divorced", "White-Collar", "White", "Female", 32, 

In [50]:
imp_r = imp.from_json(json_str)
print([o.visualize_as_dataframe(show_only_changes=True) for o in imp_r.cf_examples_list])
print(imp_r.local_importance)
print(imp_r.summary_importance)

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,50,Private,Bachelors,Married,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,46.0,-,-,-,-,-,Female,-,1
1,43.0,-,-,-,-,Other,-,-,1
2,-,-,-,-,-,-,-,96.0,1
3,-,-,-,-,-,Other,-,79.0,1
4,-,-,-,Widowed,Sales,-,-,-,1
5,63.0,-,-,-,-,Other,-,-,1
6,59.0,-,-,-,Sales,-,-,-,1
7,-,Self-Employed,-,-,Sales,-,-,-,1
8,-,-,-,-,-,-,-,90.0,1
9,-,-,-,-,-,Other,-,59.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,50,Private,HS-grad,Married,Sales,Other,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,60.0,-,Doctorate,-,-,-,-,-,1
1,68.0,-,Doctorate,-,-,-,-,-,1
2,57.0,-,Bachelors,-,-,-,-,-,1
3,-,-,Masters,-,-,-,Male,-,1
4,-,-,Assoc,-,Professional,-,-,-,1
5,-,-,Doctorate,-,-,-,-,91.0,1
6,-,-,Masters,-,-,-,-,-,1
7,-,Other/Unknown,Masters,-,-,-,-,-,1
8,-,-,Doctorate,-,Other/Unknown,-,-,-,1
9,-,-,School,-,-,-,Male,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,71,Self-Employed,Some-college,Separated,Sales,Other,Male,2,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Bachelors,-,-,-,-,56.0,1
1,-,-,-,-,-,White,-,47.0,1
2,-,-,Doctorate,Married,-,-,-,-,1
3,-,-,Prof-school,-,-,-,-,99.0,1
4,-,-,Bachelors,-,-,-,-,81.0,1
5,-,Private,-,-,-,-,-,75.0,1
6,-,-,-,-,-,White,-,48.0,1
7,-,Private,-,-,-,-,-,93.0,1
8,-,-,-,-,-,White,-,45.0,1
9,-,-,-,Married,-,-,-,51.0,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,44,Private,Prof-school,Married,Professional,White,Male,50,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Single,-,-,-,33.0,0
1,90.0,-,-,Widowed,-,-,-,-,0
2,-,-,-,Separated,-,-,-,47.0,0
3,27.0,-,Bachelors,-,-,-,-,-,0
4,-,-,-,-,Sales,-,-,15.0,0
5,20.0,-,-,-,-,-,-,-,0
6,19.0,-,HS-grad,-,-,-,-,-,0
7,22.0,-,-,-,Blue-Collar,-,-,-,0
8,18.0,-,-,-,-,-,-,-,0
9,-,-,-,Widowed,Sales,-,-,-,0

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,55,Government,Bachelors,Married,White-Collar,White,Male,38,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,23.0,-,-,-,-,-,-,-,0
1,-,-,School,-,-,-,-,69.0,0
2,88.0,-,-,-,-,-,-,-,0
3,59.0,-,-,-,-,-,-,20.0,0
4,-,-,-,Separated,-,-,-,-,0
5,-,Private,-,Divorced,-,-,-,-,0
6,25.0,-,-,-,-,-,-,-,0
7,77.0,-,-,Widowed,-,-,-,-,0
8,64.0,-,-,-,-,-,-,-,0
9,72.0,-,-,-,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,School,Married,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Other/Unknown,Doctorate,-,-,-,-,-,1
1,-,-,HS-grad,-,-,-,Female,-,1
2,-,-,Bachelors,-,-,-,-,72.0,1
3,-,-,-,-,-,Other,-,88.0,1
4,-,-,HS-grad,-,-,Other,-,-,1
5,-,-,Masters,-,-,-,Female,-,1
6,-,-,Doctorate,-,-,-,Female,-,1
7,51.0,-,Prof-school,-,-,-,-,-,1
8,-,-,Doctorate,-,-,Other,-,-,1
9,-,-,-,-,-,-,-,59.0,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,Bachelors,Married,White-Collar,White,Male,40,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,62.0,-,-,-,-,-,Female,-,0
1,73.0,-,-,Single,-,-,-,-,0
2,37.0,-,-,Single,-,-,-,-,0
3,-,-,-,Widowed,-,-,-,15.0,0
4,-,-,HS-grad,Divorced,-,-,-,-,0
5,84.0,-,-,-,Blue-Collar,-,-,-,0
6,-,-,Assoc,Single,-,-,-,-,0
7,63.0,Government,-,-,-,-,-,-,0
8,-,-,Assoc,Divorced,-,-,-,-,0
9,27.0,-,Masters,-,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,42,Private,Some-college,Divorced,White-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,-,-,52.0,1
1,-,-,-,Separated,-,-,-,57.0,1
2,-,-,-,-,-,-,-,55.0,1
3,-,-,-,Married,Blue-Collar,-,-,-,1
4,-,-,Doctorate,Single,-,-,-,-,1
5,-,-,-,-,-,-,-,88.0,1
6,-,-,-,-,-,-,-,98.0,1
7,-,-,-,Married,-,-,-,83.0,1
8,-,-,Bachelors,Married,-,-,-,-,1
9,-,-,-,-,-,-,-,86.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,33,Private,HS-grad,Single,Blue-Collar,Other,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Doctorate,-,White-Collar,-,-,-,-
1,-,-,Prof-school,-,Sales,-,Male,-,1
2,-,Government,-,Married,-,White,-,-,1
3,-,Self-Employed,-,Married,-,White,-,-,1
4,-,-,-,Married,-,White,-,97.0,1
5,70.0,-,Doctorate,-,Sales,-,-,-,1
6,56.0,-,Doctorate,-,-,-,-,19.0,1
7,-,-,Doctorate,Married,-,-,-,-,1
8,-,-,Masters,Married,-,White,-,-,1
9,-,-,Doctorate,Married,-,-,-,67.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,41,Private,HS-grad,Divorced,Service,White,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Married,-,-,Male,52.0,1
1,-,-,-,Married,-,Other,Male,-,1
2,-,-,-,Married,-,-,Male,99.0,1
3,68.0,-,-,Married,-,-,Male,-,1
4,-,-,-,Married,White-Collar,-,-,-,1
5,-,Self-Employed,-,Married,-,-,Male,-,1
6,61.0,-,-,Married,-,-,Male,-,1
7,-,-,-,Married,-,-,Male,-,1
8,-,-,-,Married,-,-,Male,43.0,1
9,-,-,-,-,White-Collar,-,Male,95.0,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,47,Government,Some-college,Married,Blue-Collar,White,Male,40,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,17.0,-,-,-,-,-,-,-,0
1,-,-,Bachelors,-,-,-,-,19.0,0
2,36.0,-,-,-,-,-,-,-,0
3,75.0,-,-,-,-,-,-,-,0
4,-,-,-,Widowed,-,-,-,27.0,0
5,-,-,-,-,-,-,-,31.0,0
6,-,Self-Employed,-,-,-,-,-,88.0,0
7,-,Self-Employed,-,-,Sales,-,-,-,0
8,68.0,-,-,-,-,-,-,-,0
9,31.0,-,-,Separated,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,69,Other/Unknown,HS-grad,Widowed,Other/Unknown,White,Female,9,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Private,Masters,Married,-,-,-,80.0,1
1,-,-,Masters,Married,-,Other,-,53.0,1
2,-,-,Doctorate,Single,Sales,-,-,-,1
3,-,-,Doctorate,Single,-,-,-,-,-
4,-,-,Masters,Married,-,-,-,83.0,1
5,-,-,-,Married,-,-,Male,53.0,1
6,-,-,Masters,Married,-,-,-,84.0,1
7,-,Private,Masters,Married,-,-,-,-,1
8,46.0,-,Doctorate,Single,Sales,-,-,-,1
9,-,Self-Employed,Doctorate,Single,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,62,Private,Assoc,Married,White-Collar,White,Female,45,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,Other/Unknown,-,-,84.0,0
1,-,-,-,Divorced,-,-,-,70.0,0
2,-,-,Bachelors,-,-,-,-,67.0,0
3,83.0,-,-,Separated,-,-,-,-,0
4,-,-,Bachelors,Widowed,-,-,-,-,0
5,44.0,-,-,Single,-,-,-,-,0
6,-,-,HS-grad,Separated,-,-,-,-,0
7,37.0,-,-,Single,-,-,-,-,0
8,-,-,-,Widowed,-,-,-,73.0,0
9,-,-,-,Separated,Other/Unknown,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,33,Self-Employed,Assoc,Married,Blue-Collar,White,Male,65,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Government,-,-,Other/Unknown,-,-,-,1
1,45.0,-,-,-,Sales,-,-,-,1
2,-,-,-,-,-,-,Female,45.0,1
3,-,-,HS-grad,-,-,-,-,98.0,1
4,57.0,-,Bachelors,-,-,-,-,-,1
5,-,Other/Unknown,-,-,White-Collar,-,-,-,1
6,-,-,-,-,Professional,-,-,63.0,1
7,52.0,-,Bachelors,-,-,-,-,-,1
8,-,Private,Bachelors,-,-,-,-,-,1
9,-,-,-,-,Sales,-,Female,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,44,Government,Assoc,Married,Blue-Collar,White,Male,30,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,Sales,-,-,85.0,1
1,63.0,-,-,-,Professional,-,-,-,1
2,-,-,HS-grad,-,White-Collar,-,-,-,1
3,-,-,Doctorate,-,Other/Unknown,-,-,-,1
4,-,-,Bachelors,-,White-Collar,-,-,-,1
5,-,-,Some-college,-,-,-,-,42.0,1
6,-,-,Prof-school,-,Professional,-,-,-,1
7,-,-,Doctorate,-,White-Collar,-,-,-,1
8,61.0,-,-,-,Professional,-,-,-,1
9,-,Other/Unknown,-,-,Professional,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,25,Private,Some-college,Single,Service,White,Male,25,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,67.0,-,Doctorate,Married,-,Other,-,-,1
1,34.0,-,-,Married,-,-,-,48.0,1
2,34.0,-,-,Married,-,-,-,98.0,1
3,-,-,-,Married,Blue-Collar,-,-,73.0,1
4,61.0,-,Doctorate,Married,-,-,-,-,1
5,-,-,Bachelors,Married,-,-,-,-,1
6,86.0,-,-,Separated,-,-,-,92.0,1
7,77.0,-,-,Married,-,-,-,91.0,1
8,84.0,-,-,Married,Professional,-,-,93.0,1
9,68.0,Self-Employed,-,Married,-,-,-,35.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,27,Private,Assoc,Single,White-Collar,White,Male,50,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Bachelors,Married,-,-,-,-,1
1,86.0,-,-,Married,-,-,-,-,1
2,34.0,-,-,Married,-,-,-,-,1
3,63.0,-,-,Married,-,-,-,-,1
4,79.0,-,-,Married,-,-,-,-,1
5,-,-,Prof-school,Married,-,-,-,-,1
6,-,-,Doctorate,Married,-,-,-,-,1
7,62.0,-,Masters,-,-,-,-,-,1
8,72.0,-,-,Married,-,-,-,-,1
9,85.0,-,Masters,-,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,44,Private,Bachelors,Married,White-Collar,White,Male,50,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,46.0,-,-,Widowed,-,-,-,-,0
1,24.0,-,-,-,-,-,-,-,0
2,-,-,School,Separated,-,-,-,-,0
3,-,-,-,Single,-,-,-,85.0,0
4,-,-,HS-grad,-,-,-,-,6.0,0
5,19.0,Government,-,-,-,-,-,-,0
6,-,-,-,Divorced,-,-,-,-,0
7,82.0,-,-,Separated,-,-,-,-,0
8,70.0,-,-,Divorced,-,-,-,-,0
9,-,Government,School,-,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,31,Private,HS-grad,Single,Blue-Collar,White,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Self-Employed,-,Married,-,-,-,-,1
1,43.0,-,-,Married,-,-,-,-,1
2,-,-,-,Married,-,-,-,-,1
3,-,Government,-,Married,-,-,-,-,1
4,-,-,-,Married,-,-,-,96.0,1
5,-,-,-,Married,-,-,-,98.0,1
6,-,-,-,Married,-,-,-,51.0,1
7,-,-,Prof-school,Married,-,-,-,-,1
8,86.0,-,Doctorate,-,-,-,-,-,1
9,-,-,-,Married,-,-,-,36.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,51,Government,HS-grad,Married,White-Collar,White,Female,32,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Doctorate,-,-,-,-,83.0,1
1,-,-,Doctorate,Divorced,-,-,-,-,1
2,35.0,-,-,-,-,-,-,-,1
3,-,-,Masters,-,Other/Unknown,-,-,-,1
4,42.0,-,Prof-school,-,-,-,-,-,1
5,68.0,-,Prof-school,-,-,-,-,-,1
6,60.0,-,-,-,-,-,-,44.0,1
7,-,-,Masters,-,Sales,-,-,-,1
8,-,-,Doctorate,-,-,Other,-,-,1
9,66.0,-,-,-,-,-,-,29.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,47,Private,Masters,Divorced,Service,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,-,-,91.0,1
1,-,Self-Employed,-,Married,-,-,-,-,1
2,-,-,-,-,-,-,-,49.0,1
3,-,-,-,-,Other/Unknown,-,-,53.0,1
4,-,-,-,-,-,-,-,92.0,1
5,-,-,-,Married,White-Collar,-,-,-,1
6,-,-,-,Married,-,Other,-,-,1
7,52.0,-,-,Married,-,-,-,-,1
8,-,-,-,-,-,Other,-,86.0,1
9,-,-,-,Married,-,-,-,50.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,50,Self-Employed,Doctorate,Married,Professional,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Other/Unknown,-,-,-,-,-,3.0,1
1,-,-,-,Single,-,Other,-,-,1
2,-,-,-,-,-,-,-,46.0,1
3,39.0,-,School,-,-,-,-,-,1
4,87.0,-,-,-,-,-,-,-,1
5,-,-,-,-,-,-,Female,76.0,1
6,-,-,-,-,Service,-,-,62.0,1
7,-,-,Some-college,-,-,Other,-,-,1
8,71.0,-,-,-,White-Collar,-,-,-,1
9,30.0,-,-,-,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,49,Private,Some-college,Married,Sales,White,Male,80,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,37.0,-,School,-,-,-,-,-,0
1,-,-,-,-,-,-,-,23.0,0
2,34.0,-,-,Single,-,-,-,-,0
3,24.0,Self-Employed,-,-,-,-,-,-,0
4,-,-,-,-,Blue-Collar,-,-,50.0,0
5,46.0,-,-,-,-,-,-,19.0,0
6,34.0,-,-,-,-,-,Female,-,0
7,-,-,-,Single,-,-,-,88.0,0
8,-,-,-,-,Blue-Collar,-,-,19.0,0
9,-,-,School,Widowed,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,22,Private,HS-grad,Single,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,58.0,Self-Employed,-,-,Service,-,-,-,1
1,60.0,-,Prof-school,Married,-,-,-,-,1
2,62.0,Self-Employed,-,-,-,-,-,-,1
3,-,-,Assoc,-,-,Other,-,-,1
4,61.0,-,-,Married,-,-,-,78.0,1
5,90.0,-,Doctorate,-,Other/Unknown,-,-,-,1
6,55.0,-,-,Separated,White-Collar,-,-,-,-
7,63.0,-,-,Divorced,-,Other,-,-,1
8,61.0,-,-,Married,-,-,-,-,1
9,61.0,Self-Employed,-,-,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,56,Private,HS-grad,Married,White-Collar,White,Male,40,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,25.0,-,-,-,-,-,-,64.0,0
1,-,-,-,Single,Other/Unknown,-,-,-,0
2,-,-,School,-,-,-,-,36.0,0
3,19.0,Other/Unknown,-,-,-,-,-,-,0
4,26.0,-,-,-,-,-,-,-,0
5,29.0,-,-,-,-,-,-,52.0,0
6,-,Self-Employed,-,-,-,-,-,95.0,0
7,46.0,-,-,-,-,-,-,-,0
8,-,-,-,Single,-,-,-,65.0,0
9,31.0,-,-,-,-,Other,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,33,Private,HS-grad,Married,Sales,White,Male,20,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Government,-,-,-,-,-,36.0,1
1,-,-,-,-,Blue-Collar,-,-,99.0,1
2,-,-,-,-,Professional,-,-,56.0,1
3,-,Government,-,-,-,-,-,70.0,1
4,-,-,-,-,Blue-Collar,-,-,51.0,1
5,54.0,-,Prof-school,-,-,-,-,-,1
6,44.0,-,-,-,-,-,-,67.0,1
7,-,-,-,-,Professional,-,-,51.0,1
8,-,-,Doctorate,-,-,-,-,86.0,1
9,-,-,-,-,-,-,-,57.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,57,Private,HS-grad,Married,Service,White,Male,30,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Government,-,-,-,-,-,82.0,1
1,-,Self-Employed,Some-college,-,-,-,-,-,1
2,-,-,Bachelors,-,-,-,-,-,1
3,-,-,-,-,Blue-Collar,-,-,73.0,1
4,65.0,-,-,-,-,-,-,65.0,1
5,-,Self-Employed,-,-,-,-,-,35.0,1
6,86.0,-,-,-,-,-,-,81.0,1
7,46.0,-,-,-,-,-,-,77.0,1
8,-,-,Doctorate,-,-,-,-,-,1
9,89.0,-,-,-,-,-,-,44.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,72,Private,Bachelors,Married,Service,White,Male,17,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,-,-,25.0,1
1,-,-,-,-,-,-,-,35.0,1
2,-,-,-,-,-,-,-,92.0,1
3,-,-,-,-,-,-,-,50.0,1
4,-,-,-,-,-,-,-,78.0,1
5,-,-,-,-,Other/Unknown,-,-,44.0,1
6,-,-,-,-,-,-,-,76.0,1
7,-,-,HS-grad,-,-,-,-,83.0,1
8,-,-,Prof-school,-,-,-,-,44.0,1
9,-,Government,-,-,-,-,-,54.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,19,Private,Some-college,Single,Service,White,Female,15,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,77.0,-,-,Married,White-Collar,-,-,-,1
1,34.0,-,-,Separated,-,-,Male,87.0,-
2,59.0,Self-Employed,Doctorate,-,Other/Unknown,-,-,-,1
3,59.0,Self-Employed,Doctorate,-,-,-,-,-,1
4,90.0,Other/Unknown,Doctorate,-,White-Collar,-,-,-,1
5,72.0,-,-,Married,White-Collar,Other,-,-,1
6,-,-,-,Married,Professional,Other,-,74.0,1
7,59.0,Self-Employed,Doctorate,-,Other/Unknown,Other,-,-,1
8,76.0,-,Doctorate,-,Blue-Collar,-,-,-,1
9,76.0,-,-,-,White-Collar,-,-,65.0,-

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,44,Private,HS-grad,Divorced,Blue-Collar,Other,Male,20,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,81.0,-,-,-,-,-,-,60.0,1
1,69.0,-,-,-,-,-,-,69.0,1
2,53.0,-,-,-,-,-,-,89.0,1
3,83.0,-,-,-,-,-,-,96.0,1
4,80.0,-,-,-,-,-,-,50.0,1
5,64.0,-,-,-,-,-,-,93.0,1
6,76.0,-,-,-,-,-,-,48.0,1
7,75.0,-,-,-,-,-,-,68.0,1
8,81.0,-,-,-,-,-,-,96.0,1
9,62.0,-,-,-,-,-,-,96.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,48,Private,Bachelors,Married,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,-,-,64.0,1
1,-,Government,-,-,-,-,Female,-,1
2,39.0,-,Some-college,-,-,-,-,-,1
3,-,-,-,-,Professional,-,-,32.0,1
4,-,-,-,-,White-Collar,-,-,-,1
5,-,-,-,-,-,-,-,90.0,1
6,72.0,-,-,-,-,Other,-,-,1
7,-,-,-,-,-,-,-,57.0,1
8,-,-,-,-,-,-,Female,83.0,1
9,70.0,-,-,-,-,Other,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,24,Private,Bachelors,Single,White-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,60.0,-,-,-,-,-,Female,-,1
1,77.0,-,-,Widowed,-,-,-,-,1
2,70.0,-,-,-,-,-,Female,-,1
3,64.0,-,-,Married,-,-,-,-,1
4,40.0,-,-,Married,-,-,-,-,1
5,76.0,-,-,-,-,-,Female,-,1
6,73.0,-,-,Married,-,-,-,-,1
7,79.0,-,-,Married,-,-,-,-,1
8,55.0,-,-,Widowed,-,-,-,-,1
9,55.0,-,-,Married,-,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,43,Government,Masters,Divorced,Professional,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Self-Employed,-,-,-,-,-,90.0,1
1,73.0,-,-,-,-,-,-,-,1
2,-,Self-Employed,-,-,-,-,-,81.0,1
3,53.0,-,-,-,-,-,-,63.0,1
4,-,-,-,Single,-,-,Female,-,1
5,-,-,-,Married,-,-,-,27.0,1
6,82.0,-,-,-,-,-,-,-,1
7,79.0,-,-,-,-,-,-,-,1
8,68.0,-,-,-,-,-,-,-,1
9,-,-,-,Married,-,Other,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,22,Private,HS-grad,Single,Blue-Collar,White,Male,35,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,53.0,-,-,Married,-,-,-,86.0,1
1,33.0,-,-,Married,-,-,-,82.0,1
2,-,-,-,Married,-,Other,-,91.0,1
3,86.0,-,-,Separated,-,-,-,53.0,1
4,41.0,-,Doctorate,Married,White-Collar,-,-,-,1
5,61.0,-,Doctorate,Married,-,Other,-,-,1
6,62.0,Other/Unknown,-,Divorced,-,-,-,53.0,1
7,-,-,Prof-school,Married,Professional,-,-,-,1
8,62.0,-,Prof-school,Separated,White-Collar,-,-,-,-
9,88.0,-,Prof-school,-,Service,Other,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,39,Private,HS-grad,Married,Blue-Collar,White,Female,40,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,Other/Unknown,-,-,-,0
1,-,-,-,Single,Service,-,-,-,0
2,-,-,-,-,-,-,Male,70.0,0
3,-,-,-,-,-,-,-,17.0,0
4,-,-,-,-,-,-,-,14.0,0
5,23.0,-,Masters,-,-,-,-,-,0
6,-,Other/Unknown,-,-,-,-,Male,-,0
7,-,Other/Unknown,-,-,-,-,-,89.0,0
8,70.0,-,-,-,-,-,-,93.0,0
9,-,-,-,-,Sales,-,-,50.0,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,HS-grad,Married,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,75.0,-,-,-,-,-,-,-,1
1,80.0,-,-,-,-,-,-,-,1
2,61.0,-,-,-,-,-,-,-,1
3,80.0,Government,-,-,-,-,-,-,1
4,55.0,-,-,-,-,-,-,-,1
5,74.0,-,-,-,-,-,-,97.0,1
6,71.0,-,-,-,-,-,-,-,1
7,-,Self-Employed,-,-,Sales,-,-,-,1
8,-,-,-,-,-,-,Female,-,1
9,49.0,Government,-,-,-,-,-,-,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,55,Private,HS-grad,Married,Blue-Collar,White,Male,53,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Single,-,-,-,45.0,0
1,-,-,-,Single,-,-,-,-,0
2,90.0,-,-,-,-,Other,-,-,0
3,-,Self-Employed,-,-,-,-,-,29.0,0
4,24.0,-,Assoc,-,-,-,-,-,0
5,84.0,-,-,-,-,-,-,-,0
6,-,Other/Unknown,-,-,White-Collar,-,-,-,0
7,71.0,-,-,Divorced,-,-,-,-,0
8,83.0,-,-,-,-,-,Female,-,0
9,-,-,-,-,Professional,-,-,86.0,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,42,Self-Employed,HS-grad,Single,White-Collar,White,Male,48,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Divorced,-,-,-,89.0,1
1,-,-,-,Divorced,-,-,-,73.0,1
2,-,-,Masters,-,-,-,Female,-,1
3,68.0,-,Doctorate,-,-,-,-,-,1
4,75.0,-,-,-,-,Other,-,-,1
5,-,-,Doctorate,-,-,-,-,27.0,1
6,37.0,-,Masters,-,-,-,-,-,1
7,-,-,-,Married,Sales,-,-,-,1
8,58.0,-,Masters,-,-,-,-,-,1
9,-,-,Masters,-,Other/Unknown,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,52,Private,HS-grad,Widowed,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Government,-,Married,-,-,-,-,1
1,-,-,-,Married,-,-,-,99.0,1
2,-,-,-,Married,-,-,-,49.0,1
3,-,-,Bachelors,-,Service,-,-,-,1
4,-,-,Bachelors,-,Other/Unknown,-,-,-,1
5,83.0,-,-,Married,-,-,-,-,1
6,60.0,-,-,Married,-,-,-,-,1
7,-,-,Prof-school,Married,-,-,-,-,1
8,61.0,-,-,Married,-,-,-,-,1
9,-,-,-,Married,-,-,-,74.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,37,Private,Masters,Single,Professional,White,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,Government,-,Married,-,-,-,-,1
1,-,-,-,Married,-,-,-,71.0,1
2,-,-,-,Married,-,-,-,99.0,1
3,-,Government,Doctorate,-,-,-,-,-,1
4,-,-,-,Married,-,-,-,76.0,1
5,73.0,-,-,-,-,-,-,83.0,1
6,-,-,-,Married,-,-,-,34.0,1
7,-,-,-,-,-,-,Male,68.0,1
8,24.0,-,-,Married,-,-,-,-,1
9,61.0,-,-,-,-,-,-,92.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,26,Private,School,Married,White-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,31.0,-,Doctorate,-,-,-,-,-,1
1,80.0,-,Doctorate,-,-,-,-,-,1
2,81.0,-,Some-college,-,-,-,-,-,1
3,46.0,Self-Employed,-,-,-,-,-,-,1
4,72.0,-,HS-grad,-,-,-,-,-,1
5,76.0,-,Masters,-,-,-,-,-,1
6,45.0,Self-Employed,-,-,-,-,-,-,1
7,59.0,-,Doctorate,-,-,-,-,-,1
8,51.0,-,-,-,Blue-Collar,-,-,-,1
9,56.0,-,Doctorate,-,-,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,38,Private,Assoc,Divorced,White-Collar,White,Female,16,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Married,-,-,-,-,1
1,-,-,-,Married,-,-,-,76.0,1
2,-,-,HS-grad,Married,-,-,-,-,-
3,50.0,-,-,Married,-,-,-,-,1
4,69.0,-,-,Married,-,-,-,-,1
5,-,-,-,Married,-,-,-,11.0,1
6,-,-,Masters,Married,-,-,-,-,1
7,-,-,Some-college,Married,-,-,-,-,1
8,65.0,-,-,Married,-,-,-,-,1
9,59.0,-,-,Married,-,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,28,Self-Employed,Some-college,Married,Blue-Collar,White,Male,55,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,54.0,-,-,-,-,-,-,-,1
1,84.0,-,-,-,-,-,-,38.0,1
2,-,-,School,-,-,Other,-,-,-
3,74.0,-,-,-,-,-,-,-,1
4,-,-,-,-,Professional,-,-,72.0,1
5,-,-,School,-,Professional,-,-,-,1
6,82.0,-,Prof-school,-,-,-,-,-,1
7,56.0,-,-,-,-,-,-,-,1
8,-,-,School,-,White-Collar,-,-,-,1
9,-,-,-,-,Service,-,-,95.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,22,Private,HS-grad,Single,Service,Other,Male,30,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,61.0,-,-,Divorced,Blue-Collar,-,-,-,1
1,79.0,-,Prof-school,-,Professional,-,-,-,1
2,76.0,Self-Employed,Prof-school,-,-,-,-,-,1
3,78.0,-,-,Separated,-,-,-,53.0,1
4,35.0,-,Prof-school,-,-,-,-,-,1
5,55.0,Self-Employed,-,-,Professional,-,-,58.0,1
6,48.0,-,Doctorate,-,-,White,Female,-,1
7,82.0,-,Prof-school,Married,-,-,-,90.0,1
8,66.0,-,Prof-school,-,-,-,-,38.0,1
9,66.0,-,-,Separated,-,-,-,84.0,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,54,Private,Bachelors,Single,Service,Other,Female,36,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,68.0,-,-,Married,Professional,-,-,-,1
1,-,-,-,Married,Blue-Collar,-,-,-,1
2,-,Government,Some-college,Married,-,-,-,-,1
3,-,-,-,Married,Professional,-,-,-,1
4,-,Other/Unknown,Prof-school,-,-,-,Male,-,1
5,-,Government,-,Married,-,-,-,76.0,1
6,-,-,Doctorate,-,White-Collar,-,-,-,1
7,-,-,-,Married,Other/Unknown,-,Male,-,1
8,-,-,-,Married,Other/Unknown,-,-,-,1
9,-,Self-Employed,-,Married,Blue-Collar,-,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,62,Private,School,Married,Sales,White,Male,35,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Masters,-,Professional,-,-,-,1
1,-,Self-Employed,-,-,-,-,-,80.0,1
2,-,-,-,-,Professional,-,-,80.0,1
3,-,-,Some-college,-,-,-,-,65.0,1
4,-,Government,Masters,-,-,-,-,-,1
5,-,Self-Employed,-,-,-,-,-,70.0,1
6,-,-,Masters,-,-,-,-,-,1
7,-,-,Bachelors,-,-,-,-,37.0,1
8,-,-,Masters,-,-,-,-,89.0,1
9,-,-,Doctorate,-,-,-,Female,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,39,Private,Bachelors,Divorced,White-Collar,White,Male,50,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,Doctorate,-,-,-,-,89.0,1
1,-,-,-,Married,-,-,-,94.0,1
2,87.0,-,HS-grad,-,-,-,-,-,1
3,70.0,-,-,Married,-,-,-,-,1
4,-,-,-,Separated,-,-,-,91.0,1
5,-,-,Masters,Widowed,-,-,-,-,1
6,47.0,-,Masters,-,-,-,-,-,1
7,-,-,-,Married,Other/Unknown,-,-,-,1
8,70.0,-,Masters,-,-,-,-,-,1
9,-,-,-,-,-,-,-,83.0,1

Query instance (original outcome : 1)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,46,Self-Employed,Doctorate,Married,Professional,White,Male,50,1

Counterfactual set (new outcome: 0.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,82.0,-,-,Separated,-,-,-,-,0
1,-,-,Some-college,Separated,-,-,-,-,0
2,-,-,Masters,Separated,-,-,-,-,0
3,-,-,HS-grad,Separated,-,-,-,-,0
4,-,-,-,Separated,-,Other,-,-,0
5,-,-,Bachelors,-,-,-,-,97.0,0
6,-,-,School,Widowed,-,-,-,-,0
7,-,-,-,Separated,-,-,Female,-,0
8,-,-,-,Divorced,-,Other,-,-,0
9,-,Other/Unknown,-,Widowed,-,-,-,-,0

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,43,Private,HS-grad,Married,Blue-Collar,White,Male,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,-,-,-,-,78.0,1
1,-,-,Bachelors,-,-,-,-,91.0,1
2,48.0,-,-,-,-,-,-,98.0,1
3,-,-,-,-,White-Collar,-,-,78.0,1
4,-,-,-,-,Professional,-,-,59.0,1
5,44.0,-,-,-,Service,-,-,-,1
6,-,-,-,-,-,-,-,53.0,1
7,56.0,-,-,-,-,-,-,-,1
8,-,-,-,-,Professional,-,-,66.0,1
9,-,-,Doctorate,-,-,Other,-,-,1

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,28,Government,Doctorate,Divorced,Professional,White,Female,40,0

Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,-,-,-,Married,-,-,-,18.0,1
1,-,-,-,Married,-,-,-,81.0,1
2,19.0,-,-,Married,-,-,-,-,1
3,-,-,-,Married,-,-,-,38.0,1
4,75.0,-,-,Widowed,-,-,-,-,1
5,-,Other/Unknown,-,Married,-,-,-,-,1
6,27.0,-,-,Married,-,-,-,-,1
7,-,-,Prof-school,Married,-,-,-,-,1
8,77.0,-,-,Separated,-,-,-,-,-
9,73.0,-,-,Married,-,-,-,-,1

[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
[{'age': 0.4, 'race': 0.4, 'hours_per_week': 0.4, 'occupation': 0.3, 'workclass': 0.1, 'marital_status': 0.1, 'gender': 0.1, 'education': 0.0}, {'education': 1.0, 'age': 0.3, 'occupation': 0.2, 'gender': 0.2, 'workclass': 0.1, 'hours_per_week': 0.1, 'marital_status': 0.0, 'race': 0.0}, {'hours_per_week': 0.9, 'education': 0.4, 'race': 0.3, 'workclass': 0.2, 'marital_status': 0.2, 'age': 0.0, 'occupation': 0.0, 'gender': 0.0}, {'age': 0.6, 'marital_status': 0.4, 'occupation': 0.3, 'hours_per_week': 0.3, 'education': 0.2, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.7, 'marital_status': 0.3, 'hours_per_week': 0.2, 'workclass': 0.1, 'education': 0.1, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.8, 'race': 0.3, 'gender': 0.3, 'hours_per_week': 0.3, 'age': 0.1, 'workclass': 0.1, 'marital_status': 0.0, 'occupation': 0.0}, {'age': 0.6, 'marital_status': 0.6, 'education': 0.4, 'workclass': 0.1, 'occupation': 0.1, 'gender': 0.1, 'hours_per_week': 0.1, 'race': 0.0}, {'hours_per_week': 0.7, 'marital_status': 0.5, 'education': 0.2, 'occupation': 0.1, 'age': 0.0, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.7, 'marital_status': 0.6, 'race': 0.4, 'occupation': 0.3, 'hours_per_week': 0.3, 'age': 0.2, 'workclass': 0.2, 'gender': 0.1}, {'marital_status': 0.9, 'gender': 0.9, 'hours_per_week': 0.4, 'age': 0.2, 'occupation': 0.2, 'workclass': 0.1, 'race': 0.1, 'education': 0.0}, {'age': 0.5, 'hours_per_week': 0.4, 'workclass': 0.2, 'marital_status': 0.2, 'education': 0.1, 'occupation': 0.1, 'race': 0.0, 'gender': 0.0}, {'marital_status': 1.0, 'education': 0.9, 'hours_per_week': 0.5, 'workclass': 0.3, 'occupation': 0.2, 'age': 0.1, 'race': 0.1, 'gender': 0.1}, {'marital_status': 0.8, 'hours_per_week': 0.4, 'age': 0.3, 'education': 0.3, 'occupation': 0.2, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'occupation': 0.5, 'education': 0.4, 'age': 0.3, 'workclass': 0.3, 'hours_per_week': 0.3, 'gender': 0.2, 'marital_status': 0.0, 'race': 0.0}, {'occupation': 0.9, 'education': 0.6, 'age': 0.2, 'hours_per_week': 0.2, 'workclass': 0.1, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'marital_status': 1.0, 'age': 0.8, 'hours_per_week': 0.7, 'education': 0.3, 'occupation': 0.2, 'workclass': 0.1, 'race': 0.1, 'gender': 0.0}, {'marital_status': 0.8, 'age': 0.7, 'education': 0.5, 'workclass': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'marital_status': 0.6, 'age': 0.5, 'education': 0.3, 'workclass': 0.2, 'hours_per_week': 0.2, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.9, 'hours_per_week': 0.4, 'age': 0.2, 'workclass': 0.2, 'education': 0.2, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'education': 0.7, 'age': 0.5, 'hours_per_week': 0.3, 'occupation': 0.2, 'marital_status': 0.1, 'race': 0.1, 'workclass': 0.0, 'gender': 0.0}, {'hours_per_week': 0.6, 'marital_status': 0.5, 'occupation': 0.2, 'race': 0.2, 'age': 0.1, 'workclass': 0.1, 'education': 0.0, 'gender': 0.0}, {'age': 0.4, 'hours_per_week': 0.4, 'education': 0.2, 'occupation': 0.2, 'race': 0.2, 'workclass': 0.1, 'marital_status': 0.1, 'gender': 0.1}, {'age': 0.5, 'hours_per_week': 0.5, 'marital_status': 0.3, 'education': 0.2, 'occupation': 0.2, 'workclass': 0.1, 'gender': 0.1, 'race': 0.0}, {'age': 0.9, 'marital_status': 0.5, 'workclass': 0.3, 'education': 0.3, 'occupation': 0.3, 'race': 0.2, 'hours_per_week': 0.1, 'gender': 0.0}, {'age': 0.6, 'hours_per_week': 0.5, 'workclass': 0.2, 'marital_status': 0.2, 'education': 0.1, 'occupation': 0.1, 'race': 0.1, 'gender': 0.0}, {'hours_per_week': 0.9, 'occupation': 0.4, 'age': 0.2, 'workclass': 0.2, 'education': 0.2, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 0.7, 'age': 0.4, 'workclass': 0.3, 'education': 0.3, 'occupation': 0.1, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 1.0, 'education': 0.2, 'workclass': 0.1, 'occupation': 0.1, 'age': 0.0, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.9, 'occupation': 0.8, 'education': 0.5, 'workclass': 0.4, 'marital_status': 0.4, 'race': 0.3, 'hours_per_week': 0.3, 'gender': 0.1}, {'age': 1.0, 'hours_per_week': 1.0, 'workclass': 0.0, 'education': 0.0, 'marital_status': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 0.5, 'age': 0.3, 'occupation': 0.2, 'race': 0.2, 'gender': 0.2, 'workclass': 0.1, 'education': 0.1, 'marital_status': 0.0}, {'age': 1.0, 'marital_status': 0.7, 'gender': 0.3, 'workclass': 0.0, 'education': 0.0, 'occupation': 0.0, 'race': 0.0, 'hours_per_week': 0.0}, {'age': 0.5, 'hours_per_week': 0.4, 'marital_status': 0.3, 'workclass': 0.2, 'race': 0.1, 'gender': 0.1, 'education': 0.0, 'occupation': 0.0}, {'marital_status': 0.9, 'age': 0.8, 'education': 0.5, 'hours_per_week': 0.5, 'occupation': 0.4, 'race': 0.3, 'workclass': 0.1, 'gender': 0.0}, {'hours_per_week': 0.6, 'occupation': 0.3, 'age': 0.2, 'workclass': 0.2, 'gender': 0.2, 'education': 0.1, 'marital_status': 0.1, 'race': 0.0}, {'age': 0.8, 'workclass': 0.3, 'occupation': 0.1, 'gender': 0.1, 'hours_per_week': 0.1, 'education': 0.0, 'marital_status': 0.0, 'race': 0.0}, {'age': 0.5, 'marital_status': 0.3, 'hours_per_week': 0.3, 'workclass': 0.2, 'occupation': 0.2, 'education': 0.1, 'race': 0.1, 'gender': 0.1}, {'education': 0.6, 'age': 0.4, 'marital_status': 0.3, 'hours_per_week': 0.3, 'occupation': 0.2, 'race': 0.1, 'gender': 0.1, 'workclass': 0.0}, {'marital_status': 0.8, 'age': 0.3, 'education': 0.3, 'hours_per_week': 0.3, 'occupation': 0.2, 'workclass': 0.1, 'race': 0.0, 'gender': 0.0}, {'hours_per_week': 0.7, 'marital_status': 0.6, 'age': 0.3, 'workclass': 0.2, 'education': 0.1, 'gender': 0.1, 'occupation': 0.0, 'race': 0.0}, {'age': 1.0, 'education': 0.7, 'workclass': 0.2, 'occupation': 0.1, 'marital_status': 0.0, 'race': 0.0, 'gender': 0.0, 'hours_per_week': 0.0}, {'marital_status': 1.0, 'age': 0.4, 'education': 0.3, 'hours_per_week': 0.2, 'workclass': 0.0, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}, {'age': 0.5, 'education': 0.4, 'occupation': 0.4, 'hours_per_week': 0.3, 'race': 0.1, 'workclass': 0.0, 'marital_status': 0.0, 'gender': 0.0}, {'age': 1.0, 'education': 0.6, 'hours_per_week': 0.5, 'marital_status': 0.4, 'occupation': 0.3, 'workclass': 0.2, 'race': 0.1, 'gender': 0.1}, {'marital_status': 0.8, 'occupation': 0.7, 'workclass': 0.4, 'education': 0.3, 'gender': 0.2, 'age': 0.1, 'hours_per_week': 0.1, 'race': 0.0}, {'education': 0.7, 'hours_per_week': 0.6, 'workclass': 0.3, 'occupation': 0.2, 'gender': 0.1, 'age': 0.0, 'marital_status': 0.0, 'race': 0.0}, {'education': 0.5, 'marital_status': 0.5, 'age': 0.4, 'hours_per_week': 0.4, 'occupation': 0.1, 'workclass': 0.0, 'race': 0.0, 'gender': 0.0}, {'marital_status': 0.9, 'education': 0.5, 'race': 0.2, 'age': 0.1, 'workclass': 0.1, 'gender': 0.1, 'hours_per_week': 0.1, 'occupation': 0.0}, {'hours_per_week': 0.7, 'occupation': 0.4, 'age': 0.3, 'education': 0.2, 'race': 0.1, 'workclass': 0.0, 'marital_status': 0.0, 'gender': 0.0}, {'marital_status': 1.0, 'age': 0.5, 'hours_per_week': 0.3, 'workclass': 0.1, 'education': 0.1, 'occupation': 0.0, 'race': 0.0, 'gender': 0.0}]
{'age': 0.432, 'hours_per_week': 0.4, 'marital_status': 0.392, 'education': 0.324, 'occupation': 0.2, 'workclass': 0.138, 'race': 0.082, 'gender': 0.08}